// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ffTestStatistic
NumericVector ffTestStatistic(const NumericMatrix& S1, const NumericMatrix& S2, std::vector<double> W, /** sc changed here **/                               char method);
RcppExport SEXP _fasano_franceschini_test_ffTestStatistic(SEXP S1SEXP, SEXP S2SEXP, SEXP WSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S1(S1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S2(S2SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type W(WSEXP);
    Rcpp::traits::input_parameter< /** sc changed here **/                               char >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(ffTestStatistic(S1, S2, W, method));
    return rcpp_result_gen;
END_RCPP
}
// permutationTestSeeded
unsigned int permutationTestSeeded(const NumericMatrix& S1, const NumericMatrix& S2, std::vector<double> W, /** sc changed here **/                                    int nPermute, bool verbose, char method, int seed);
RcppExport SEXP _fasano_franceschini_test_permutationTestSeeded(SEXP S1SEXP, SEXP S2SEXP, SEXP WSEXP, SEXP nPermuteSEXP, SEXP verboseSEXP, SEXP methodSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S1(S1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S2(S2SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type W(WSEXP);
    Rcpp::traits::input_parameter< /** sc changed here **/                                    int >::type nPermute(nPermuteSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< char >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(permutationTestSeeded(S1, S2, W, nPermute, verbose, method, seed));
    return rcpp_result_gen;
END_RCPP
}
// permutationTest
unsigned int permutationTest(const NumericMatrix& S1, const NumericMatrix& S2, std::vector<double> W, /** sc changed here **/                              int nPermute, bool verbose, char method);
RcppExport SEXP _fasano_franceschini_test_permutationTest(SEXP S1SEXP, SEXP S2SEXP, SEXP WSEXP, SEXP nPermuteSEXP, SEXP verboseSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S1(S1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S2(S2SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type W(WSEXP);
    Rcpp::traits::input_parameter< /** sc changed here **/                              int >::type nPermute(nPermuteSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< char >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(permutationTest(S1, S2, W, nPermute, verbose, method));
    return rcpp_result_gen;
END_RCPP
}
// permutationTestParallel
unsigned int permutationTestParallel(const NumericMatrix& S1, const NumericMatrix& S2, std::vector<double> W, /** sc changed here **/                                      int nPermute, char method);
RcppExport SEXP _fasano_franceschini_test_permutationTestParallel(SEXP S1SEXP, SEXP S2SEXP, SEXP WSEXP, SEXP nPermuteSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S1(S1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S2(S2SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type W(WSEXP);
    Rcpp::traits::input_parameter< /** sc changed here **/                                      int >::type nPermute(nPermuteSEXP);
    Rcpp::traits::input_parameter< char >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(permutationTestParallel(S1, S2, W, nPermute, method));
    return rcpp_result_gen;
END_RCPP
}
// permutationTestParallelSeeded
unsigned int permutationTestParallelSeeded(const NumericMatrix& S1, const NumericMatrix& S2, std::vector<double> W, /** sc changed here **/                                            int nPermute, char method, int seed);
RcppExport SEXP _fasano_franceschini_test_permutationTestParallelSeeded(SEXP S1SEXP, SEXP S2SEXP, SEXP WSEXP, SEXP nPermuteSEXP, SEXP methodSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S1(S1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S2(S2SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type W(WSEXP);
    Rcpp::traits::input_parameter< /** sc changed here **/                                            int >::type nPermute(nPermuteSEXP);
    Rcpp::traits::input_parameter< char >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(permutationTestParallelSeeded(S1, S2, W, nPermute, method, seed));
    return rcpp_result_gen;
END_RCPP
}
// parallelVectorSum
double parallelVectorSum(NumericVector x);
RcppExport SEXP _fasano_franceschini_test_parallelVectorSum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(parallelVectorSum(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fasano_franceschini_test_ffTestStatistic", (DL_FUNC) &_fasano_franceschini_test_ffTestStatistic, 4},
    {"_fasano_franceschini_test_permutationTestSeeded", (DL_FUNC) &_fasano_franceschini_test_permutationTestSeeded, 7},
    {"_fasano_franceschini_test_permutationTest", (DL_FUNC) &_fasano_franceschini_test_permutationTest, 6},
    {"_fasano_franceschini_test_permutationTestParallel", (DL_FUNC) &_fasano_franceschini_test_permutationTestParallel, 5},
    {"_fasano_franceschini_test_permutationTestParallelSeeded", (DL_FUNC) &_fasano_franceschini_test_permutationTestParallelSeeded, 6},
    {"_fasano_franceschini_test_parallelVectorSum", (DL_FUNC) &_fasano_franceschini_test_parallelVectorSum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fasano_franceschini_test(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
